/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ruft den aktuellen Status und die Daten des Antrags ab
         * @description Das Frontend ruft dies initial auf und pollt diesen Endpunkt (z.B. alle 3s), um zu prüfen, ob 'validationStatus' von 'IN_PROGRESS' auf 'COMPLETED' gewechselt ist.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    applicationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Erfolgreiche Rückgabe */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApplicationState"];
                    };
                };
                /** @description Antrag nicht gefunden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/start-validation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Startet den Validierungsprozess explizit
         * @description Dient dazu, den Prozess explizit zu starten, damit das Polling (GET) rein lesend bleibt.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    applicationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prozess gestartet */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Validation started */
                            message: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Antrag endgültig einreichen (trotz evtl. Warnungen) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    applicationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Erfolgreich eingereicht */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            submissionId: string;
                            /** @example SUBMITTED */
                            status: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/applications/{applicationId}/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ruft die kompletten Antragsdaten für die Validierung ab */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    applicationId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Antragsdaten */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApplicationData"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lädt ein Dokument herunter */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    documentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Datei-Inhalt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                        "image/jpeg": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/applications/{applicationId}/validation-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Callback für die FaaS Cloud Function
         * @description Die Cloud Function ruft diesen Endpunkt auf, wenn sie fertig gerechnet hat.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    applicationId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
            responses: {
                /** @description Ergebnis empfangen und in DB gespeichert */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApplicationState: {
            id: string;
            /** @example Max Mustermann */
            applicantName: string;
            applicant: components["schemas"]["ApplicantDetails"];
            /**
             * @description Der globale Status des Antrags
             * @enum {string}
             */
            status: "DRAFT" | "VALIDATING" | "READY_TO_SUBMIT" | "READY_TO_SUBMIT_WITH_PROBLEMS" | "SUBMITTED";
            validationReport: components["schemas"]["ValidationReport"];
            /** @description Rohdaten aus DB (Gehalt, Zertifikate etc.) zur Anzeige */
            submittedData: {
                uploadedDocuments: components["schemas"]["DocumentMetadata"][];
            };
        };
        ValidationReport: {
            /**
             * @description Applicant ID
             * @example 0123
             */
            applicationId?: string;
            /**
             * @description True, wenn die Cloud Function fertig ist.
             * @example true
             */
            isComplete: boolean;
            /**
             * @description Ampel-Status für das gesamte Formular.
             * @enum {string}
             */
            overallResult: "PENDING" | "SUCCESS" | "WARNING" | "CRITICAL_ERROR";
            /** Format: date-time */
            checkedAt: string;
            checks: components["schemas"]["CheckResult"][];
        };
        CheckResult: {
            /** @example Language Certificate */
            documentTitle: string;
            /** @example salary_slip */
            type?: string;
            /** @example Validity */
            checkDisplayTitle: string;
            /** @enum {string} */
            status: "PASS" | "FAIL";
            /**
             * @description Text für den User, warum es fehlgeschlagen ist.
             * @example Das Einkommen der letzten 3 Monate ist zu gering.
             */
            message: string;
        };
        DocumentMetadata: {
            docId: string;
            /** @example salary_slip */
            type: string;
            filename: string;
            /** @description Link zum Anzeigen im Frontend */
            url: string;
        };
        ApplicantDetails: {
            /** @example Max */
            firstName: string;
            /** @example Mustermann */
            lastName: string;
            /** @example max@example.com */
            email: string;
            /** @example Musterstraße 1, 80331 München */
            address: string;
            /** @example United Kingdom */
            nationality: string;
        };
        ApplicationData: {
            applicationId: string;
            applicant: components["schemas"]["ApplicantDetails"];
            submittedDocuments: components["schemas"]["DocumentMetadata"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
