// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApplicationsByApplicationIdData, GetApplicationsByApplicationIdErrors, GetApplicationsByApplicationIdResponses, GetInternalApplicationsByApplicationIdDataData, GetInternalApplicationsByApplicationIdDataResponses, GetInternalDocumentsByDocumentIdData, GetInternalDocumentsByDocumentIdResponses, PostApplicationsByApplicationIdStartValidationData, PostApplicationsByApplicationIdStartValidationResponses, PostApplicationsByApplicationIdSubmitData, PostApplicationsByApplicationIdSubmitResponses, PostInternalApplicationsByApplicationIdValidationResultData, PostInternalApplicationsByApplicationIdValidationResultResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Ruft den aktuellen Status und die Daten des Antrags ab
 *
 * Das Frontend ruft dies initial auf und pollt diesen Endpunkt (z.B. alle 3s), um zu prüfen, ob 'validationStatus' von 'IN_PROGRESS' auf 'COMPLETED' gewechselt ist.
 *
 */
export const getApplicationsByApplicationId = <ThrowOnError extends boolean = false>(options: Options<GetApplicationsByApplicationIdData, ThrowOnError>) => (options.client ?? client).get<GetApplicationsByApplicationIdResponses, GetApplicationsByApplicationIdErrors, ThrowOnError>({ url: '/applications/{applicationId}', ...options });

/**
 * Startet den Validierungsprozess explizit
 *
 * Dient dazu, den Prozess explizit zu starten, damit das Polling (GET) rein lesend bleibt.
 *
 */
export const postApplicationsByApplicationIdStartValidation = <ThrowOnError extends boolean = false>(options: Options<PostApplicationsByApplicationIdStartValidationData, ThrowOnError>) => (options.client ?? client).post<PostApplicationsByApplicationIdStartValidationResponses, unknown, ThrowOnError>({ url: '/applications/{applicationId}/start-validation', ...options });

/**
 * Antrag endgültig einreichen (trotz evtl. Warnungen)
 */
export const postApplicationsByApplicationIdSubmit = <ThrowOnError extends boolean = false>(options: Options<PostApplicationsByApplicationIdSubmitData, ThrowOnError>) => (options.client ?? client).post<PostApplicationsByApplicationIdSubmitResponses, unknown, ThrowOnError>({ url: '/applications/{applicationId}/submit', ...options });

/**
 * Ruft die kompletten Antragsdaten für die Validierung ab
 */
export const getInternalApplicationsByApplicationIdData = <ThrowOnError extends boolean = false>(options: Options<GetInternalApplicationsByApplicationIdDataData, ThrowOnError>) => (options.client ?? client).get<GetInternalApplicationsByApplicationIdDataResponses, unknown, ThrowOnError>({ url: '/internal/applications/{applicationId}/data', ...options });

/**
 * Lädt ein Dokument herunter
 */
export const getInternalDocumentsByDocumentId = <ThrowOnError extends boolean = false>(options: Options<GetInternalDocumentsByDocumentIdData, ThrowOnError>) => (options.client ?? client).get<GetInternalDocumentsByDocumentIdResponses, unknown, ThrowOnError>({ url: '/internal/documents/{documentId}', ...options });

/**
 * Callback für die FaaS Cloud Function
 *
 * Die Cloud Function ruft diesen Endpunkt auf, wenn sie fertig gerechnet hat.
 */
export const postInternalApplicationsByApplicationIdValidationResult = <ThrowOnError extends boolean = false>(options: Options<PostInternalApplicationsByApplicationIdValidationResultData, ThrowOnError>) => (options.client ?? client).post<PostInternalApplicationsByApplicationIdValidationResultResponses, unknown, ThrowOnError>({
    url: '/internal/applications/{applicationId}/validation-result',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
