// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://hackatum-api-254788991896.europe-west3.run.app/api/v1' | 'http://localhost:3000/api/v1' | (string & {});
};

export type ApplicationState = {
    id: string;
    applicantName: string;
    applicant: ApplicantDetails;
    /**
     * Der globale Status des Antrags
     */
    status: 'DRAFT' | 'VALIDATING' | 'READY_TO_SUBMIT' | 'READY_TO_SUBMIT_WITH_PROBLEMS' | 'SUBMITTED';
    validationReport: ValidationReport;
    /**
     * Rohdaten aus DB (Gehalt, Zertifikate etc.) zur Anzeige
     */
    submittedData: {
        uploadedDocuments: Array<DocumentMetadata>;
    };
};

export type ValidationReport = {
    /**
     * True, wenn die Cloud Function fertig ist.
     */
    isComplete: boolean;
    /**
     * Ampel-Status für das gesamte Formular.
     */
    overallResult: 'PENDING' | 'SUCCESS' | 'WARNING' | 'CRITICAL_ERROR';
    checkedAt: string;
    checks: Array<CheckResult>;
};

export type CheckResult = {
    checkId: string;
    title: string;
    status: 'PASS' | 'FAIL' | 'WARNING' | 'PENDING';
    /**
     * Text für den User, warum es fehlgeschlagen ist.
     */
    message: string;
    /**
     * Optionaler Pointer auf das Feld, das falsch ist.
     */
    affectedField: string;
};

export type DocumentMetadata = {
    docId: string;
    type: string;
    filename: string;
    /**
     * Link zum Anzeigen im Frontend
     */
    url: string;
};

export type ApplicantDetails = {
    firstName: string;
    lastName: string;
    email: string;
    address: string;
    nationality: string;
};

export type ApplicationData = {
    applicationId: string;
    applicant: ApplicantDetails;
    submittedDocuments: Array<DocumentMetadata>;
};

export type GetApplicationsByApplicationIdData = {
    body?: never;
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/applications/{applicationId}';
};

export type GetApplicationsByApplicationIdErrors = {
    /**
     * Antrag nicht gefunden
     */
    404: unknown;
};

export type GetApplicationsByApplicationIdResponses = {
    /**
     * Erfolgreiche Rückgabe
     */
    200: ApplicationState;
};

export type GetApplicationsByApplicationIdResponse = GetApplicationsByApplicationIdResponses[keyof GetApplicationsByApplicationIdResponses];

export type PostApplicationsByApplicationIdStartValidationData = {
    body?: never;
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/applications/{applicationId}/start-validation';
};

export type PostApplicationsByApplicationIdStartValidationResponses = {
    /**
     * Prozess gestartet
     */
    202: {
        message: string;
    };
};

export type PostApplicationsByApplicationIdStartValidationResponse = PostApplicationsByApplicationIdStartValidationResponses[keyof PostApplicationsByApplicationIdStartValidationResponses];

export type PostApplicationsByApplicationIdSubmitData = {
    body?: never;
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/applications/{applicationId}/submit';
};

export type PostApplicationsByApplicationIdSubmitResponses = {
    /**
     * Erfolgreich eingereicht
     */
    200: {
        submissionId: string;
        status: string;
    };
};

export type PostApplicationsByApplicationIdSubmitResponse = PostApplicationsByApplicationIdSubmitResponses[keyof PostApplicationsByApplicationIdSubmitResponses];

export type GetInternalApplicationsByApplicationIdDataData = {
    body?: never;
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/internal/applications/{applicationId}/data';
};

export type GetInternalApplicationsByApplicationIdDataResponses = {
    /**
     * Antragsdaten
     */
    200: ApplicationData;
};

export type GetInternalApplicationsByApplicationIdDataResponse = GetInternalApplicationsByApplicationIdDataResponses[keyof GetInternalApplicationsByApplicationIdDataResponses];

export type GetInternalDocumentsByDocumentIdData = {
    body?: never;
    path: {
        documentId: string;
    };
    query?: never;
    url: '/internal/documents/{documentId}';
};

export type GetInternalDocumentsByDocumentIdResponses = {
    /**
     * Datei-Inhalt
     */
    200: Blob | File;
};

export type GetInternalDocumentsByDocumentIdResponse = GetInternalDocumentsByDocumentIdResponses[keyof GetInternalDocumentsByDocumentIdResponses];

export type PostInternalApplicationsByApplicationIdValidationResultData = {
    body: ValidationReport;
    path: {
        applicationId: string;
    };
    query?: never;
    url: '/internal/applications/{applicationId}/validation-result';
};

export type PostInternalApplicationsByApplicationIdValidationResultResponses = {
    /**
     * Ergebnis empfangen und in DB gespeichert
     */
    200: unknown;
};
